### ISSUE TITLE
Create an `api-proxy` workspace

### ISSUE THREAD

**Issue by jdomingos** [litentry/api-gateway#85]
Create a separate workspace for an `api-proxy` to isolate the functioning of the APIs, so that we can eventually serve it either from different subdomain or separate path.
This will let us run a different instance of the API for that context and isolate it from errors that might happen in other application instances.

**Comment by geastwood** [comment]
Each sub package has to be stitched together still as a single graphql instance yeh?

I guess I haven't seen how the structure gonna look like.

**Comment by bdmason** [comment]
Yes and no. The squid stuff has issues, and I asked @franjs if they were keen on using this in production soon. By enabling the proxy independently (as well as through the gateway) they can use it in production and I don't have to worry about causing them issues, so I can focus on resolving the squid issues. I still haven't got round to testing the scenario where 1 remote schema goes down, if it brings the gateway down we need a solution to ensure the issue is isolated.

Give me a call on slack if you want a quick chat about the issues I'm facing.

**Comment by jdomingos** [comment]
After an investigation by @markdavison, it was verified that the proxy continued to work even if another schema is broken.
That renders this work useless, as we are now confident in deploying it together with the 3rd party schemas.

/cc @bdmason
